language: cpp

env:
  - tbs_arch=x86
  - tbs_arch=x64

os:
  - linux
#  - osx

before_install:
  - if [ "$tbs_arch" = "x86" ];
    then
      sudo apt-get update -qq;
      sudo apt-get -y install gcc-multilib;
    fi

script:
  - ./scripts/thumbs make
  - ./scripts/thumbs check
  - ./scripts/thumbs check2
