version: 1.6.14.{build}
shallow_clone: true


environment:
  matrix:
    - tbs_arch: "x86"
      tbs_tools: "msvc12"
      tbs_static_runtime: 0
    
    - tbs_arch: "x64"
      tbs_tools: "msvc12"
      tbs_static_runtime: 0
    
    - tbs_arch: "x86"
      tbs_tools: "mingw"
      tbs_static_runtime: 1
    
    - tbs_arch: "x64"
      tbs_tools: "mingw"
      tbs_static_runtime: 1



install:
  - ps: if($env:tbs_arch -eq 'x64') {
          $env:vcvar_arg = 'x86_amd64';
        }
        elseif($env:tbs_arch -eq 'x86') {
          $env:vcvar_arg = 'x86';
        }
  
  # get common functions
  - git clone https://github.com/imazen/gd-appveyor-helpers
  - ps: . .\gd-appveyor-helpers\appveyor_funcs.ps1
  
  # get mingw-w64 (C:\mingw64)
  # copy of http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.1/threads-posix/seh/x86_64-4.9.1-release-posix-seh-rt_v3-rev1.7z
  - ps: if($env:tbs_tools -eq 'mingw' -and $env:tbs_arch -eq 'x64')
        {
          curl -outfile mw64.7z "http://libgd.blob.core.windows.net/mingw/x86_64-4.9.1-release-posix-seh-rt_v3-rev1.7z";
          if((Get-FileHash mw64.7z -Algorithm SHA1).Hash -ne "91A35AE296C1A71802AB0C7228EE57F9AAC5D7C7")
          {
            echo "Invalid file hash";
            exit 1;
          };
          7z x -oC:\ mw64.7z | out-null;
        }
  
  # fetch deps
  - nuget install zlib-%tbs_tools%-%tbs_arch%-master -Source https://ci.appveyor.com/nuget/zlib-94hmpf3q011d
  - move zlib* zlib
  - if [%tbs_tools%]==[mingw] move zlib\libzlibstatic.a zlib\libz.a
  - if [%tbs_tools%]==[msvc12] move zlib\zlibstatic.lib zlib\zlib.lib
  
  - SET tbsd_zlib_built=1
  - SET tbsd_zlib_incdir=zlib
  - SET tbsd_zlib_libdir=zlib



build_script:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall" %vcvar_arg%'
  - if [%tbs_tools%]==[mingw] if [%tbs_arch%]==[x86] SET PATH=C:\MinGW\bin;%PATH%
  - if [%tbs_tools%]==[mingw] if [%tbs_arch%]==[x64] SET PATH=C:\mingw64\bin;%PATH%
  
  - SET zip=libpng-%tbs_tools%-%tbs_arch%.zip
  - ps: $nupkg_b = "libpng-$($env:tbs_tools)-$($env:tbs_arch)-$($env:APPVEYOR_REPO_BRANCH)";
  - ps: $nupkg_c = "libpng-$($env:tbs_tools)-$($env:tbs_arch)-$($env:APPVEYOR_REPO_COMMIT)";
  
  - scripts\thumbs make
  - for /f "tokens=*" %%i in ('scripts\thumbs list') do set files=%%i
  - 7z a %zip% %files%
  - appveyor PushArtifact %zip%
  
  - ps: if(Test-Path $env:zip) {
          zip2nuget $env:zip $nupkg_b;
          zip2nuget $env:zip $nupkg_c; }



test_script:
  - SET fail=0
  
  - scripts\thumbs check || SET fail=1 & ver > nul
  - ps: Push-Ctest-Results 'build'
  - ps: Push-AppveyorArtifact build\Testing\Temporary\LastTest.log
  
  - scripts\thumbs check2 || SET fail=1 & ver > nul
  - ps: Push-Ctest-Results 'pngsuite'
  
  - exit %fail%


on_success:
  - ps: Push-AppveyorArtifact "$nupkg_b*.nupkg"
  - ps: Push-AppveyorArtifact "$nupkg_c*.nupkg"
